DOMinatorz/Grace-Shopper

README.md
=> just messing around

README.md
=> getting it back to normal

.travis.yml, package.json
=> updated json / travis files to the name of our project

package-lock.json, script/seed.js, server/db/models/user.js
=> Users model

client/app.js, client/components/all-bracelets.js, client/store/bracelet.js, client/store/index.js, script/seed.js, server/db/models/bracelet.js
=> updated all components page to render all of the bracelets

client/app.js, client/components/all-bracelets.js, client/components/single-bracelet.js, client/routes.js
* added single bracelet page with routes and links
=> single bracelet view

client/components/single-bracelet.js
updated the single bracelet component to be a class instead of a functional component
=> Bracelet front end updating single bracelet component

public/index.html
=> changing title

.travis.yml, client/components/user-home.spec.js
=> travis activate deployment

.travis.yml, client/components/user-home.spec.js, server/api/users.spec.js, server/db/models/user.spec.js
=> tests passing

.travis.yml
=> travis updated

client/components/cart.js, client/components/single-bracelet.js, client/routes.js, client/store/addToCart.js, client/store/index.js, script/seed.js
=> Bracelets add to cart

.gitignore, server/db/models/index.js
=> Cart model

server/api/cart.js, server/api/index.js, server/db/models/index.js
=> started on routes for the cart -need to be tested

client/components/all-bracelets.js, client/routes.js, package-lock.json, server/api/index.js, server/db/models/bracelet.js, server/db/models/index.js, server/db/models/user.js, server/index.js
=> Sarah's comments

server/db/models/bracelet.js, server/db/models/cart.js, server/db/models/index.js
=> updating models, created cart model

script/seed.js, server/db/models/bracelet.js, server/db/models/cart.js, server/db/models/index.js, server/db/models/items-cart.js
=> finished updating models and seed file

server/api/cart.js
=> cart routes added

server/api/cart.js
=> added route to add item to cart

client/components/cart.js, client/components/single-bracelet.js, client/store/addToCart.js, client/store/bracelet.js, client/store/index.js, server/api/cart.js
=> User cart data from backend

server/api/cart.js
=> updated decrement and delete routes

server/api/index.js
=> fixing travis hopefully

server/api/index.js, server/api/users.js, server/api/utils.js
=> Security checks

client/app.js, client/components/cart.js, client/components/index.js, client/routes.js, package-lock.json, package.json, public/index.html, server/api/bracelets.js, server/api/cart.js, server/api/index.js, server/api/users.js, server/index.js, webpack.config.js
=> added basic bootstrap

server/api/users.js
=> updated user route to pass travis tests

client/components/guestSingleBracelet.js, package-lock.json, script/seed.js
=> updated seed

client/components/GuestCart.js, client/components/GuestCheckout.js, client/components/UserCheckout.js, client/components/cart.js, client/routes.js, client/store/addToCart.js, client/store/bracelet.js, script/seed.js, server/api/cart.js, server/api/checkout.js, server/api/index.js, server/index.js
=> Checkout - guest checkout implemented user checkout in progress (almost done)

server/api/cart.js
=> updated delete route

client/store/bracelet.js, server/api/checkout.js
=> checkout guest now recorded, values passed through req.body

server/api/cart.js, server/api/checkout.js, server/db/models/cart.js
=> allhistory working now

client/components/all-bracelets.css, client/components/all-bracelets.js
=> Filter functionality

client/components/accountPage.js
=> order history done

client/routes.js
=> added a minor redirect

client/components/LandingPage.js, client/components/all-bracelets.css, client/components/landing-page.css
=> added additional page and title to landing page

client/components/GuestCart.js, client/components/cart.js, client/components/single-bracelet.css
=> updating cart to not show bracelet id

client/components/all-bracelets.js
=> moved position of filter titles

client/components/all-bracelets.css, client/components/all-bracelets.js, client/components/auth-form.css
=> search field and clear button styled, login form corrected

client/components/GuestCheckout.js, client/components/navbar.js, public/index.html
=> changed title on main page and on the tab

client/components/GuestCheckout.js, client/components/UserCheckout.js
=> fixed redirects
